server.port: 8081

spring:
  application.name: temperature-processing
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  data:
    mongodb:
      uri: mongodb://localhost:27017/sensors